
--1..  What are the total number of orders and total revenue generated?

select 
count(Order_ID) as no_of_orders,
round(sum(Total_Amount),2)  as tot_revenue
from sales_fact


--Q2.  Which cities generate the highest number of orders?

select 
c.city ,
count(s.Order_ID) as total_orders 
from customers c
join sales_fact as s
on c.Customer_ID = s.Customer_ID
group by city 
order by total_orders desc

--Q3  what is the total revenue generated by each product category 

select
p.Category,
sum(s.Total_Amount) as total_revenue
from sales_fact as s
join products as p
on p.Product_ID = s.Product_ID
group by p.Category
order by total_revenue DESC


-- Q4.  Which low-rated sellers (rating below 3) are still generating high revenue?

select Top 5
s.seller_ID,
se.Rating,
round(sum(s.Total_Amount) ,2) as high_revenue
from sales_fact as s
join sellers as se on s.Seller_ID = se.Seller_ID
where se.Rating < 3
group by s.seller_ID ,se.Rating
order by high_revenue DESC


-- Q5.  What are the top 10 best-selling products by quantity sold?

select top 10
       p.Product_Name,
       p.Category,
       sum(s.Quantity) as tot_qua_sold
from products as p
join sales_fact as s
  on p.Product_ID = s.Product_ID
group by p.Product_Name, p.Category
order by tot_qua_sold desc;


-- Q6.  Find the top 3 selling products (by revenue) in each category.

select * 
from (
select 
p.Category , P.Product_Name ,
round(sum(s.Total_Amount) ,2) as total_revenue ,
rank() over( partition by p.Category Order by sum(s.Total_Amount) DESC ) as rn 
from sales_fact as s
join Products as p
on p.Product_ID = s.Product_ID
group by p.Category , P.Product_Name
) ranking
where rn <= 3

-- Q7.  Calculate a running (cumulative) total of daily revenue over time.

select 
Order_date ,
sum(Total_Amount) as total_daily_revenue ,
sum(sum(Total_Amount)) over( order by Order_Date) running_total
from sales_fact
group by Order_Date


-- Q8.  What is the year-over-year (YoY) revenue growth?

WITH annual_revenue AS (
    -- Step 1: Calculate total revenue for each year
    SELECT 
        YEAR(order_date) AS sales_year,
        SUM(Total_Amount) AS total_revenue
    FROM sales_fact
    GROUP BY YEAR(order_date)
)
-- Step 2: Use LAG to pull the prior year's revenue and calculate growth %
SELECT 
    sales_year,
    total_revenue,
    LAG(total_revenue, 1) OVER (ORDER BY sales_year) AS prior_year_revenue,
    ROUND(
        100.0 * (total_revenue - LAG(total_revenue, 1) OVER (ORDER BY sales_year)) 
        / NULLIF(LAG(total_revenue, 1) OVER (ORDER BY sales_year), 0), 
		2
    ) AS yoy_growth_pct
FROM annual_revenue
ORDER BY sales_year;



--Q9.
--Rank sellers by revenue and show each seller's percentile standing.

-- USING SELLER ID 
select 
Seller_ID,
sum(Total_Amount) as revenue,
rank() over(order by sum(Total_Amount)) as total_revenue
from sales_fact
group by Seller_ID


-- Q10.  What is the monthly and yearly sales trend?

select 
year(Order_Date) as yyear,
month(Order_Date) as MMonth,
round(sum(Total_Amount), 2) as revenue 
from sales_fact
group by year(Order_Date), month(Order_Date)
Order by month(Order_Date)



-- Q11. 
--Categorize orders into High / Medium / Low value segments.

SELECT 
    CASE 
        WHEN Total_Amount >= 5000.00 THEN 'High'
        WHEN Total_Amount BETWEEN 1000 AND 4999.99 THEN 'Medium' -- Fixed overlap bug
        ELSE 'Low'
    END AS value_segment,
    COUNT(*) AS no_order,
    ROUND(SUM(Total_Amount), 2) AS segment_revenue
FROM sales_fact
GROUP BY 
    CASE 
        WHEN Total_Amount >= 5000.00 THEN 'High'
        WHEN Total_Amount BETWEEN 1000 AND 4999.99 THEN 'Medium'
        ELSE 'Low'
    END
ORDER BY segment_revenue DESC;

-- Q12. 
-- Label each age group as a High/Medium/Low spender based on average order value.

-- with CASE 
select 
c.Age_Group,
  CASE
    WHEN AVG(s.Total_Amount) > 4000 THEN 'High Spender'
    WHEN AVG(s.Total_Amount) BETWEEN 2000 AND 4000 THEN 'Medium Spender'
    ELSE 'Low Spender'
  END AS Spending_Category,
round(avg(Total_Amount), 2) as avg_order_value
from sales_fact as s
join customers as c 
on c.Customer_ID = s.Customer_ID
group by c.Age_Group
order by avg(Total_Amount) DESC





-- Q13.  Find customers whose total spend is above the average customer spend.

SELECT DISTINCT
    Customer_ID, 
    total_spend_by_customer
FROM (
    SELECT 
        Customer_ID, 
        round(SUM(Total_Amount) OVER(PARTITION BY Customer_ID) ,2) AS total_spend_by_customer
    FROM sales_fact
) AS inner_query
WHERE total_spend_by_customer > (
    SELECT
	AVG(Total_Amount) 
    FROM sales_fact
) 
ORDER BY total_spend_by_customer DESC;


-- Q14. 
-- Combine the Top-5 customers by revenue with the 
-- Top-5 by order count into one labeled list.

use flipkart_sales
SELECT Customer_ID, Metric_Value, 'Top by Revenue' AS List_Type
FROM (
  SELECT TOP 5 Customer_ID, SUM(Total_Amount) AS Metric_Value
  FROM sales_fact
  GROUP BY Customer_ID
  ORDER BY Metric_Value DESC
) AS top_revenue

UNION

SELECT Customer_ID, Metric_Value, 'Top by Order Count' AS List_Type
FROM (
  SELECT TOP 5 Customer_ID, COUNT(*) AS Metric_Value
  FROM sales_fact
  GROUP BY Customer_ID
  ORDER BY Metric_Value DESC
) AS top_orders;



-- Q15.  Find the best-selling product category for each month.

WITH monthly_category_revenue AS (
  SELECT FORMAT(s.Order_Date, 'yyyy-MM') AS Month,
         p.Category,
         SUM(s.Total_Amount) AS Revenue
  FROM sales_fact s
  JOIN products p ON s.Product_ID = p.Product_ID
  GROUP BY FORMAT(s.Order_Date, 'yyyy-MM'), p.Category
),
ranked AS (
  SELECT Month, Category, Revenue,
         RANK() OVER (PARTITION BY Month ORDER BY Revenue DESC) AS rnk
  FROM monthly_category_revenue
)
SELECT Month, Category, Revenue
FROM ranked
WHERE rnk = 1
ORDER BY Month;

